### ISSUE TITLE
Create example quiz app

### ISSUE THREAD

**Issue by nibalizer** [Call-for-Code/Solution-Starter-Kit-Education-2020#1]
Lets make a simple app that lets you create and take quizzes

- [x] basic app
- [x] write up
- [x] architecture diagram

**Comment by derekteay** [comment]
Architecture diagram provided by @nibalizer. 

@lizklipp, FYI.

![quiz-architecture-diagram](https://user-images.githubusercontent.com/970087/77481335-d40b0e00-6df9-11ea-89c3-fc72b1bfc9d5.png)

**Comment by derekteay** [comment]
Updated with annotations, this can be further edited, if needed.

1. User navigates to the site
2. The user is presented with a website, a React frontend
3a. The user performs an action within the Express app
3b. The LoopBack Generated Code performs the necessary task within the Express app
4. Changes are saved in a PluggableDB

![quiz-architecture-diagram-updated](https://user-images.githubusercontent.com/970087/77481963-34e71600-6dfb-11ea-90c9-fa4bd8cb7171.png)

**Comment by derekteay** [comment]
A beautified architecture diagram from Glenn 

![Education workstream](https://user-images.githubusercontent.com/970087/77590588-7263a600-6ec4-11ea-9f69-32303038e210.png)

**Comment by derekteay** [comment]
@nibalizer can you provide an update on this, possibly with some screenshots?

**Comment by nibalizer** [comment]
![image](https://user-images.githubusercontent.com/195179/77630360-e29c1700-6f18-11ea-81a5-03aa297a839e.png)
![image](https://user-images.githubusercontent.com/195179/77630413-f778aa80-6f18-11ea-890c-d712bc99cabc.png)
![image](https://user-images.githubusercontent.com/195179/77630454-1414e280-6f19-11ea-91a4-929ff74a74c8.png)

**Comment by nibalizer** [comment]
https://github.com/Call-for-Code/cfc-covid-19-quiz-app and fixed!
